version: '3.9'
services:
  metabase-cratedb:
    image: metabase/metabase-enterprise:v1.45.3
    container_name: metabase-cratedb
    hostname: metabase
    volumes: 
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-app-db"
      - "MB_EMAIL_SMTP_HOST=maildev-sub"
      - "MB_EMAIL_SMTP_PASSWORD=password"
      - "MB_EMAIL_SMTP_PORT=25"
      - "MB_EMAIL_SMTP_SECURITY=none"
      - "MB_EMAIL_SMTP_USERNAME=admin"
      - "MB_PREMIUM_EMBEDDING_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - "MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE=FALSE"
    cpus: 1
    mem_limit: 1024mb
    networks: 
      - metanet1-cratedb
    depends_on: 
      postgres-app-db:
        condition: service_healthy
      cratedb:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres-app-db:
    image: postgres:15.2-alpine
    container_name: postgres-app-db
    hostname: postgres-app-db
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    networks: 
      - metanet1-cratedb
    cpus: 1
    mem_limit: 128m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  setup-cratedb:
    image: bash:5.1.16
    container_name: setup-cratedb
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1-cratedb
    depends_on:
      metabase-cratedb:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m
  maildev-sub-cratedb:
    image: maildev/maildev:1.1.0
    container_name: maildev-sub-cratedb
    hostname: maildev-sub
    ports:
    - "3001:80"
    networks:
    - metanet1-cratedb
    cpus: 1
    mem_limit: 128m
  cratedb:
    image: crate:5.2.2
    container_name: cratedb
    hostname: cratedb
    ports:
    - 4200:4200
    - 5432:5432
    networks:
    - metanet1-cratedb
    command: -Cdiscovery.type=single-node
    cpus: 2
    mem_limit: 4096mb
    healthcheck:
      test: ["CMD-SHELL", "crash -c 'select name from sys.cluster;'"]
      interval: 10s
      timeout: 5s
      retries: 5
  crash:
    build: crash/.
    container_name: crash
    hostname: crash
    networks:
    - metanet1-cratedb
    volumes: 
      - $PWD/crash:/tmp
    command: sh /tmp/populate.sh
    cpus: 1
    mem_limit: 256m
    depends_on:
      cratedb:
        condition: service_healthy
networks: 
  metanet1-cratedb:
    driver: bridge
